AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        ARTICLES_TABLE: !Ref ArticlesTable
        BEDROCK_REGION: ap-northeast-2
        CLAUDE_MODEL_ID: anthropic.claude-3-5-sonnet-20240620-v1:0

Resources:
  ArticlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: category
          AttributeType: S
        - AttributeName: publishedAt
          AttributeType: S
        - AttributeName: link
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: category-publishedAt-index
          KeySchema:
            - AttributeName: category
              KeyType: HASH
            - AttributeName: publishedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: link-index
          KeySchema:
            - AttributeName: link
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY

  RSSCollectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/rss-collector/
      Handler: index.handler
      Runtime: nodejs20.x
      Timeout: 900
      MemorySize: 1024
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ArticlesTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: 
                - 'arn:aws:bedrock:ap-northeast-2::inference-profile/*'
                - 'arn:aws:bedrock:ap-northeast-2::foundation-model/*'

  NewsAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/news-api/
      Handler: index.handler
      Runtime: nodejs20.x
      Events:
        Api:
          Type: Api
          Properties:
            Path: /articles
            Method: get
        ApiById:
          Type: Api
          Properties:
            Path: /articles/{id}
            Method: get
        ServicesApi:
          Type: Api
          Properties:
            Path: /services
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ArticlesTable

Outputs:
  NewsApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"